import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FloatingNav } from "@/app/components/ui/floating-navbar";
import { AuthProvider } from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  { name: "Home", href: "/" },
  { name: "Industry Insights", href: "/dashboard" },
  {
    name: "Success Toolkit",
    dropdown: [
      { label: "Resume Builder", href: "/resume-builder" },
      { label: "Career Roadmaps", href: "/roadmaps" },
      { label: "Interview Prep", href: "/interview" },
    ],
  },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <AuthProvider>
          <div className="flex items-center justify-start py-4 px-6">
            <h1 className="text-sm md:text-md lg:text-xl font-bold text-neutral-900 dark:text-neutral-400 mt-4 px-4 py-2 rounded-lg
            ">
              IgniteX
            </h1>
          </div>
          <FloatingNav navItems={navItems} />

          <main className="min-h-screen">{children}</main>

          <footer className="py-8 ">
            <div className="container mx-auto px-4 text-center text-gray-400">
              <p>Made with ❤️ by Anwesha</p>
              <p className="mt-2">© 2025 • All Rights Reserved</p>
            </div>
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
