import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";
import { FloatingNav } from "@/app/components/ui/floating-navbar";
import { AuthProvider } from "./context/AuthContext";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const navItems = [
  { name: "Home", href: "/" },
  { name: "Industry Insights", href: "/dashboard" },
  { name: "Success Toolkit", 
    dropdown: [
      { label: "Resume Builder", href: "/resume-builder" },
      { label: "Career Roadmaps", href: "/roadmaps" },
      { label: "Interview Prep", href: "/interview" },
    ]
   },
]
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Link href="/" className="flex items-center">
          <Image
            src="/logo.png"
            alt="Logo"
            width={105}
            height={40}
            className="object-contain ml-4 
               w-20 sm:w-24 md:w-28 lg:w-28 
               h-auto"
          />
        </Link>
        <FloatingNav navItems={navItems}/>
        <main className="min-h-screen">{children}</main>
        <footer className="py-8">
          <div className="container mx-auto px-4 text-center text-gray-400">
            <p>
              Made with ❤️ by Anwesha
            </p>
            <p className="mt-2">© 2025 • All Rights Reserved</p>
          </div>
        </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
