import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FloatingNav } from "@/app/components/ui/floating-navbar";
import { AuthProvider } from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const navItems = [
  { name: "Home", href: "/" },
  { name: "Industry", href: "/industry" },
  { name: "About", href: "/about" },
  { name: "Resume", href: "/resume" },
]
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        <FloatingNav navItems={navItems}/>
        <main className="min-h-screen">{children}</main>
        <footer className="py-8">
          <div className="container mx-auto px-4 text-center text-gray-400">
            <p>
              Made with ❤️ by Anwesha
            </p>
            <p className="mt-2">© 2025 • All Rights Reserved</p>
          </div>
        </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
